import { ItemDef, BlockType } from '../types.ts';

export const ITEMS: Record<string, ItemDef> = {
  // --- Resources ---
  dirt: {
    id: 'dirt',
    name: 'Грунт',
    category: 'resource',
    description: 'Обычный инопланетный грунт. Пригоден для простейших насыпей.',
    iconColor: '#64748b',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.DIRT,
    rarity: 'common',
  },
  stone: {
    id: 'stone',
    name: 'Камень',
    category: 'resource',
    description: 'Плотная порода. Базовый строительный и ремесленный материал.',
    iconColor: '#94a3b8',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.STONE,
    rarity: 'common',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Медная руда',
    category: 'resource',
    description: 'Проводящий металл, необходимый для создания электроники и инструментов.',
    iconColor: '#f59e0b',
    stackable: true,
    maxStack: 999,
    rarity: 'common',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Железная руда',
    category: 'resource',
    description: 'Прочный конструкционный металл для брони и каркасов.',
    iconColor: '#cbd5e1',
    stackable: true,
    maxStack: 999,
    rarity: 'uncommon',
  },
  cyan_crystal: {
    id: 'cyan_crystal',
    name: 'Светящийся кристалл',
    category: 'resource',
    description: 'Природный источник фотонной энергии. Светится мягким неоном.',
    iconColor: '#06b6d4',
    stackable: true,
    maxStack: 999,
    rarity: 'rare',
  },

  // Ares Resources
  crimson_rock: {
    id: 'crimson_rock',
    name: 'Багровый камень',
    category: 'resource',
    description: 'Термостойкая порода с Красной планеты.',
    iconColor: '#ef4444',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.CRIMSON_ROCK,
    rarity: 'uncommon',
  },
  basalt: {
    id: 'basalt',
    name: 'Вулканический базальт',
    category: 'resource',
    description: 'Тяжелый закаленный базальт.',
    iconColor: '#44403c',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.BASALT,
    rarity: 'uncommon',
  },
  energy_mineral: {
    id: 'energy_mineral',
    name: 'Энергетический минерал',
    category: 'resource',
    description: 'Высокоактивный кристалл, питающий передовые плазменные технологии.',
    iconColor: '#f97316',
    stackable: true,
    maxStack: 999,
    rarity: 'rare',
  },
  titanium_ore: {
    id: 'titanium_ore',
    name: 'Титановая руда',
    category: 'resource',
    description: 'Легкий и невероятно прочный металл высокой категории.',
    iconColor: '#e2e8f0',
    stackable: true,
    maxStack: 999,
    rarity: 'rare',
  },
  magma_core: {
    id: 'magma_core',
    name: 'Ядро магмы',
    category: 'resource',
    description: 'Пульсирующий огненный сгусток высокой температуры.',
    iconColor: '#dc2626',
    stackable: true,
    maxStack: 999,
    rarity: 'epic',
  },

  // Void Resources
  void_stone: {
    id: 'void_stone',
    name: 'Обсидиан Пустоты',
    category: 'resource',
    description: 'Абсорбирует свет и гравитационные колебания.',
    iconColor: '#7c3aed',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.VOID_STONE,
    rarity: 'rare',
  },
  void_crystal: {
    id: 'void_crystal',
    name: 'Кристалл Бездны',
    category: 'resource',
    description: 'Резонирует с пространственными разломами.',
    iconColor: '#c084fc',
    stackable: true,
    maxStack: 999,
    rarity: 'epic',
  },
  astrite_ore: {
    id: 'astrite_ore',
    name: 'Астрит',
    category: 'resource',
    description: 'Сверхплотный звездный минерал, найденный только на Пустоши.',
    iconColor: '#f43f5e',
    stackable: true,
    maxStack: 999,
    rarity: 'epic',
  },
  dark_matter: {
    id: 'dark_matter',
    name: 'Темная материя',
    category: 'resource',
    description: 'Таинственная субстанция, искривляющая физические законы.',
    iconColor: '#a855f7',
    stackable: true,
    maxStack: 999,
    rarity: 'legendary',
  },
  alien_relic: {
    id: 'alien_relic',
    name: 'Инопланетная реликвия',
    category: 'resource',
    description: 'Артефакт древней космической цивилизации.',
    iconColor: '#eab308',
    stackable: true,
    maxStack: 99,
    rarity: 'epic',
  },

  // Boss Keys / Progress
  warp_drive: {
    id: 'warp_drive',
    name: 'Варп-Двигатель',
    category: 'key',
    description: 'Дроп с Древнего Стража Ядра. Позволяет кораблю совершать гиперпрыжки на Красную планету!',
    iconColor: '#38bdf8',
    stackable: false,
    rarity: 'legendary',
  },
  hyper_core: {
    id: 'hyper_core',
    name: 'Квантовое Гиперядро',
    category: 'key',
    description: 'Дроп с Пламенного Левиафана. Открывает гиперпространственный туннель к Пустоши!',
    iconColor: '#f97316',
    stackable: false,
    rarity: 'legendary',
  },
  void_heart: {
    id: 'void_heart',
    name: 'Сердце Пустоты',
    category: 'key',
    description: 'Трофей победы над Омега-Оверлордом. Знак покорителя галактики!',
    iconColor: '#c084fc',
    stackable: false,
    rarity: 'legendary',
  },

  // --- Tools & Pickaxes ---
  starter_drill: {
    id: 'starter_drill',
    name: 'Ручной бур Mk.1',
    category: 'tool',
    description: 'Базовый инструмент для добычи рыхлых пород и камня.',
    iconColor: '#38bdf8',
    stackable: false,
    miningPower: 1,
    rarity: 'common',
  },
  plasma_pickaxe: {
    id: 'plasma_pickaxe',
    name: 'Плазменная кирка Mk.2',
    category: 'tool',
    description: 'Режет твердый титан и минералы лазерным лезвием в 2.5 раза быстрее.',
    iconColor: '#fb923c',
    stackable: false,
    miningPower: 2.5,
    rarity: 'rare',
  },
  quantum_disintegrator: {
    id: 'quantum_disintegrator',
    name: 'Квантовый дезинтегратор',
    category: 'tool',
    description: 'Моментально расщепляет любые породы и темную материю.',
    iconColor: '#c084fc',
    stackable: false,
    miningPower: 4.5,
    rarity: 'legendary',
  },

  // --- Weapons ---
  plasma_blade: {
    id: 'plasma_blade',
    name: 'Плазменный клинок',
    category: 'weapon',
    description: 'Энергетический меч ближнего боя. Наносит сильный рубящий урон по дуге.',
    iconColor: '#06b6d4',
    stackable: false,
    damage: 25,
    rarity: 'uncommon',
  },
  pulse_pistol: {
    id: 'pulse_pistol',
    name: 'Импульсный бластер',
    category: 'weapon',
    description: 'Стреляет скоростными лазерными зарядами на среднюю дистанцию.',
    iconColor: '#38bdf8',
    stackable: false,
    damage: 18,
    isRanged: true,
    energyCost: 6,
    rarity: 'uncommon',
  },
  magma_cleaver: {
    id: 'magma_cleaver',
    name: 'Магматический тесак',
    category: 'weapon',
    description: 'Тяжелый меч из сплава базальта и магмы. Поджигает врагов.',
    iconColor: '#ef4444',
    stackable: false,
    damage: 48,
    rarity: 'rare',
  },
  laser_carbine: {
    id: 'laser_carbine',
    name: 'Лазерный карабин «Фотон»',
    category: 'weapon',
    description: 'Автоматический карабин с высоким темпом стрельбы.',
    iconColor: '#fbbf24',
    stackable: false,
    damage: 32,
    isRanged: true,
    energyCost: 9,
    rarity: 'epic',
  },
  void_cannon: {
    id: 'void_cannon',
    name: 'Пустотный аннигилятор',
    category: 'weapon',
    description: 'Запускает сгустки темной энергии с гигантским уроном по области.',
    iconColor: '#a855f7',
    stackable: false,
    damage: 85,
    isRanged: true,
    energyCost: 20,
    rarity: 'legendary',
  },

  // --- Armor ---
  suit_scout: {
    id: 'suit_scout',
    name: 'Скафандр «Разведчик»',
    category: 'armor',
    description: 'Укрепленный экзокостюм: +30 к здоровью, +10% к скорости.',
    iconColor: '#0ea5e9',
    stackable: false,
    defense: 6,
    healAmount: 30, // HP bonus
    speedBonus: 0.1,
    rarity: 'uncommon',
  },
  suit_hazard: {
    id: 'suit_hazard',
    name: 'Экзоскелет «Титан»',
    category: 'armor',
    description: 'Тяжелая броня из титанового сплава: +70 к здоровью, защита от огня.',
    iconColor: '#ea580c',
    stackable: false,
    defense: 16,
    healAmount: 70,
    speedBonus: 0.05,
    rarity: 'epic',
  },
  suit_void: {
    id: 'suit_void',
    name: 'Квантовый скафандр «Апогей»',
    category: 'armor',
    description: 'Вершина защитных технологий: +150 к здоровью, колоссальная защита.',
    iconColor: '#9333ea',
    stackable: false,
    defense: 30,
    healAmount: 150,
    speedBonus: 0.2,
    rarity: 'legendary',
  },

  // --- Boosters ---
  jetpack_mk1: {
    id: 'jetpack_mk1',
    name: 'Реактивный ранец Mk.1',
    category: 'armor',
    description: 'Позволяет совершать двойной прыжок и удерживать высоту в воздухе.',
    iconColor: '#38bdf8',
    stackable: false,
    speedBonus: 0.15,
    rarity: 'rare',
  },
  jetpack_mk2: {
    id: 'jetpack_mk2',
    name: 'Гравитационный ранец Mk.2',
    category: 'armor',
    description: 'Неограниченный парящий полет при расходе энергии скафандра.',
    iconColor: '#a855f7',
    stackable: false,
    speedBonus: 0.35,
    rarity: 'legendary',
  },

  // --- Consumables & Drinks ---
  nano_medkit: {
    id: 'nano_medkit',
    name: 'Нано-тоник «Био-Реген»',
    category: 'consumable',
    description: 'Целебный нано-напиток. Можно выпить в инвентаре для мгновенного восстановления 60 HP.',
    iconColor: '#10b981',
    stackable: true,
    maxStack: 99,
    healAmount: 60,
    isDrinkable: true,
    drinkType: 'heal',
    rarity: 'common',
  },
  energy_stim: {
    id: 'energy_stim',
    name: 'Космо-Энергетик «Гипер-Драйв»',
    category: 'consumable',
    description: 'Освежающий энергетический напиток. Моментально восстанавливает 100% энергии скафандра.',
    iconColor: '#38bdf8',
    stackable: true,
    maxStack: 99,
    healAmount: 0,
    isDrinkable: true,
    drinkType: 'energy',
    rarity: 'uncommon',
  },
  space_cola: {
    id: 'space_cola',
    name: 'Космо-Кола «Звездная пыль»',
    category: 'consumable',
    description: 'Освежающая шипучая газировка космонавтов. Восстанавливает 40 HP и 60% энергии.',
    iconColor: '#f43f5e',
    stackable: true,
    maxStack: 99,
    healAmount: 40,
    isDrinkable: true,
    drinkType: 'cola',
    rarity: 'common',
  },
  speed_tonic: {
    id: 'speed_tonic',
    name: 'Антигравитационный тоник',
    category: 'consumable',
    description: 'Бодрящий напиток с фотонными частицами. Увеличивает скорость передвижения на +35% на 45 сек.',
    iconColor: '#eab308',
    stackable: true,
    maxStack: 99,
    isDrinkable: true,
    drinkType: 'speed',
    rarity: 'rare',
  },
  shield_elixir: {
    id: 'shield_elixir',
    name: 'Плазменная сыворотка щита',
    category: 'consumable',
    description: 'Укрепляющий защитный эликсир. Формирует силовой энергощит прочностью 60 единиц.',
    iconColor: '#06b6d4',
    stackable: true,
    maxStack: 99,
    isDrinkable: true,
    drinkType: 'shield',
    rarity: 'rare',
  },
  magma_brew: {
    id: 'magma_brew',
    name: 'Магматический грог Ареса',
    category: 'consumable',
    description: 'Горячий эликсир вулканических недр. Восстанавливает 100 HP и дает +12 брони на 60 сек.',
    iconColor: '#ea580c',
    stackable: true,
    maxStack: 99,
    healAmount: 100,
    isDrinkable: true,
    drinkType: 'magma',
    rarity: 'epic',
  },
  void_nectar: {
    id: 'void_nectar',
    name: 'Нектар Бездны',
    category: 'consumable',
    description: 'Легендарный эликсир Пустоты. Моментально восстанавливает 150 HP, 100% энергии и дает щит +50 ед.',
    iconColor: '#c084fc',
    stackable: true,
    maxStack: 99,
    healAmount: 150,
    isDrinkable: true,
    drinkType: 'void',
    rarity: 'legendary',
  },

  // --- Building Blocks ---
  block_tech_panel: {
    id: 'block_tech_panel',
    name: 'Технологическая панель',
    category: 'block',
    description: 'Герметичный строительный блок для создания космической базы.',
    iconColor: '#38bdf8',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.TECH_PANEL,
    rarity: 'common',
  },
  block_reinforced_metal: {
    id: 'block_reinforced_metal',
    name: 'Металлический блок',
    category: 'block',
    description: 'Укрепленная металлическая плита для оборонительных сооружений.',
    iconColor: '#94a3b8',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.REINFORCED_METAL,
    rarity: 'uncommon',
  },
  block_nano_glass: {
    id: 'block_nano_glass',
    name: 'Нано-стекло',
    category: 'block',
    description: 'Прозрачное бронированное стекло с легким синим отливом.',
    iconColor: '#7dd3fc',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.NANO_GLASS,
    rarity: 'uncommon',
  },
  block_neon_light: {
    id: 'block_neon_light',
    name: 'Светящийся блок',
    category: 'block',
    description: 'Яркий фотонный блок, освещающий темные пещеры и коридоры базы.',
    iconColor: '#06b6d4',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.NEON_LIGHT,
    rarity: 'rare',
  },
  block_base_plate: {
    id: 'block_base_plate',
    name: 'Плита обшивки',
    category: 'block',
    description: 'Гладкая металлопластиковая плита пола и потолка.',
    iconColor: '#475569',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.BASE_PLATING,
    rarity: 'common',
  },
  ladder: {
    id: 'ladder',
    name: 'Энерго-трап',
    category: 'block',
    description: 'Платформа-лестница, сквозь которую можно прыгать вверх.',
    iconColor: '#38bdf8',
    stackable: true,
    maxStack: 999,
    blockType: BlockType.LADDER,
    rarity: 'common',
  },
};
