import { BlockType, BlockDef } from '../types.ts';

export const BLOCK_SIZE = 32; // In screen pixels

export const BLOCK_DEFS: Record<BlockType, BlockDef> = {
  [BlockType.AIR]: {
    type: BlockType.AIR,
    name: 'Воздух',
    hardness: 0,
    color: 'transparent',
    solid: false,
    dropItem: '',
  },
  [BlockType.GRASS]: {
    type: BlockType.GRASS,
    name: 'Инопланетная трава',
    hardness: 0.6,
    color: '#059669', // Emerald/cyan green
    edgeColor: '#34d399',
    solid: true,
    dropItem: 'dirt',
  },
  [BlockType.DIRT]: {
    type: BlockType.DIRT,
    name: 'Грунт',
    hardness: 0.8,
    color: '#475569',
    edgeColor: '#334155',
    solid: true,
    dropItem: 'dirt',
  },
  [BlockType.STONE]: {
    type: BlockType.STONE,
    name: 'Камень',
    hardness: 1.5,
    color: '#334155',
    edgeColor: '#1e293b',
    solid: true,
    dropItem: 'stone',
  },
  [BlockType.COPPER_ORE]: {
    type: BlockType.COPPER_ORE,
    name: 'Медная руда',
    hardness: 2.0,
    color: '#b45309',
    edgeColor: '#f59e0b',
    solid: true,
    dropItem: 'copper_ore',
  },
  [BlockType.IRON_ORE]: {
    type: BlockType.IRON_ORE,
    name: 'Железная руда',
    hardness: 2.5,
    color: '#64748b',
    edgeColor: '#94a3b8',
    solid: true,
    dropItem: 'iron_ore',
  },
  [BlockType.CYAN_CRYSTAL]: {
    type: BlockType.CYAN_CRYSTAL,
    name: 'Люминесцентный кристалл',
    hardness: 2.2,
    color: '#06b6d4',
    edgeColor: '#67e8f9',
    light: 0.9,
    solid: true,
    dropItem: 'cyan_crystal',
  },
  [BlockType.BASE_WALL]: {
    type: BlockType.BASE_WALL,
    name: 'Стена базы',
    hardness: 3.0,
    color: '#1e293b',
    edgeColor: '#38bdf8',
    solid: true,
    dropItem: 'block_tech_panel',
  },
  [BlockType.BASE_PLATING]: {
    type: BlockType.BASE_PLATING,
    name: 'Плита обшивки',
    hardness: 2.5,
    color: '#334155',
    edgeColor: '#0ea5e9',
    solid: true,
    dropItem: 'block_base_plate',
  },

  // Ares (Red Planet) Blocks
  [BlockType.CRIMSON_ROCK]: {
    type: BlockType.CRIMSON_ROCK,
    name: 'Багровый камень',
    hardness: 2.5,
    color: '#7f1d1d',
    edgeColor: '#dc2626',
    solid: true,
    dropItem: 'crimson_rock',
  },
  [BlockType.BASALT]: {
    type: BlockType.BASALT,
    name: 'Вулканический базальт',
    hardness: 3.2,
    color: '#292524',
    edgeColor: '#57534e',
    solid: true,
    dropItem: 'basalt',
  },
  [BlockType.ENERGY_MINERAL]: {
    type: BlockType.ENERGY_MINERAL,
    name: 'Энергетический минерал',
    hardness: 3.0,
    color: '#ea580c',
    edgeColor: '#fb923c',
    light: 0.8,
    solid: true,
    dropItem: 'energy_mineral',
  },
  [BlockType.TITANIUM_ORE]: {
    type: BlockType.TITANIUM_ORE,
    name: 'Титановая руда',
    hardness: 4.0,
    color: '#71717a',
    edgeColor: '#e4e4e7',
    solid: true,
    dropItem: 'titanium_ore',
  },
  [BlockType.MAGMA_CORE]: {
    type: BlockType.MAGMA_CORE,
    name: 'Ядро магмы',
    hardness: 3.5,
    color: '#b91c1c',
    edgeColor: '#f97316',
    light: 1.0,
    solid: true,
    dropItem: 'magma_core',
  },
  [BlockType.HEAT_GLASS]: {
    type: BlockType.HEAT_GLASS,
    name: 'Термостекло',
    hardness: 1.8,
    color: 'rgba(251, 146, 60, 0.45)',
    edgeColor: '#fb923c',
    solid: true,
    dropItem: 'heat_glass',
  },

  // Void Planet Blocks
  [BlockType.VOID_STONE]: {
    type: BlockType.VOID_STONE,
    name: 'Обсидиан Пустоты',
    hardness: 3.8,
    color: '#2e1065',
    edgeColor: '#7c3aed',
    solid: true,
    dropItem: 'void_stone',
  },
  [BlockType.VOID_CRYSTAL]: {
    type: BlockType.VOID_CRYSTAL,
    name: 'Кристалл Бездны',
    hardness: 4.2,
    color: '#9333ea',
    edgeColor: '#c084fc',
    light: 0.95,
    solid: true,
    dropItem: 'void_crystal',
  },
  [BlockType.ASTRITE_ORE]: {
    type: BlockType.ASTRITE_ORE,
    name: 'Астрит',
    hardness: 5.0,
    color: '#4c1d95',
    edgeColor: '#e879f9',
    light: 0.7,
    solid: true,
    dropItem: 'astrite_ore',
  },
  [BlockType.DARK_MATTER]: {
    type: BlockType.DARK_MATTER,
    name: 'Темная материя',
    hardness: 5.5,
    color: '#09090b',
    edgeColor: '#a855f7',
    light: 0.6,
    solid: true,
    dropItem: 'dark_matter',
  },
  [BlockType.COSMIC_PANEL]: {
    type: BlockType.COSMIC_PANEL,
    name: 'Космическая панель',
    hardness: 4.5,
    color: '#18181b',
    edgeColor: '#8b5cf6',
    solid: true,
    dropItem: 'cosmic_panel',
  },

  // Craftable blocks
  [BlockType.TECH_PANEL]: {
    type: BlockType.TECH_PANEL,
    name: 'Технологическая панель',
    hardness: 2.0,
    color: '#0f172a',
    edgeColor: '#38bdf8',
    solid: true,
    dropItem: 'block_tech_panel',
  },
  [BlockType.REINFORCED_METAL]: {
    type: BlockType.REINFORCED_METAL,
    name: 'Металлический блок',
    hardness: 3.5,
    color: '#475569',
    edgeColor: '#94a3b8',
    solid: true,
    dropItem: 'block_reinforced_metal',
  },
  [BlockType.NANO_GLASS]: {
    type: BlockType.NANO_GLASS,
    name: 'Нано-стекло',
    hardness: 1.2,
    color: 'rgba(56, 189, 248, 0.4)',
    edgeColor: '#38bdf8',
    solid: true,
    dropItem: 'block_nano_glass',
  },
  [BlockType.NEON_LIGHT]: {
    type: BlockType.NEON_LIGHT,
    name: 'Светящийся блок',
    hardness: 1.5,
    color: '#06b6d4',
    edgeColor: '#ffffff',
    light: 1.0,
    solid: true,
    dropItem: 'block_neon_light',
  },
  [BlockType.SPACESHIP_HULL]: {
    type: BlockType.SPACESHIP_HULL,
    name: 'Корпус шаттла',
    hardness: 99.0, // Indestructible spaceship parts
    color: '#0284c7',
    edgeColor: '#38bdf8',
    solid: true,
    dropItem: '',
  },
  [BlockType.LADDER]: {
    type: BlockType.LADDER,
    name: 'Энерго-трап',
    hardness: 1.0,
    color: '#38bdf8',
    solid: false,
    isPlatform: true,
    dropItem: 'ladder',
  },
};
