import { PlanetConfig, PlanetId } from '../types.ts';

export const PLANETS: Record<PlanetId, PlanetConfig> = {
  nova: {
    id: 'nova',
    name: 'Nova Prime',
    russianName: 'Планета 1 — Новая',
    tagline: 'Колыбель исследований',
    themeColor: '#06b6d4',
    accentColor: '#10b981',
    skyGradient: ['#041c2c', '#083344', '#0f766e'],
    surfaceColor: '#059669',
    gravity: 0.5,
    bossName: 'Древний Страж Ядра',
    bossKeyItem: 'warp_drive',
    description: 'Относительно безопасная планета с пышной биолюминесцентной флорой, богатыми залежами меди, железа и фотонных кристаллов. Здесь расположена стартовая база экспедиции.',
  },
  ares: {
    id: 'ares',
    name: 'Ares Rubicon',
    russianName: 'Планета 2 — Красная',
    tagline: 'Раскаленный рубеж',
    themeColor: '#ea580c',
    accentColor: '#ef4444',
    skyGradient: ['#1c0a00', '#431407', '#991b1b'],
    surfaceColor: '#7f1d1d',
    gravity: 0.46,
    bossName: 'Пламенный Левиафан',
    bossKeyItem: 'hyper_core',
    requiredItemToVisit: 'warp_drive',
    description: 'Опасный мир вулканических разломов и базальтовых пиков. Содержит энергоресурсы высокой мощности и титан. Требуется Варп-Двигатель.',
  },
  void: {
    id: 'void',
    name: 'Nebula Void',
    russianName: 'Планета 3 — Пустошь',
    tagline: 'Край известного космоса',
    themeColor: '#9333ea',
    accentColor: '#c084fc',
    skyGradient: ['#050014', '#1e1035', '#3b0764'],
    surfaceColor: '#2e1065',
    gravity: 0.38,
    bossName: 'Омега-Оверлорд',
    bossKeyItem: 'void_heart',
    requiredItemToVisit: 'hyper_core',
    description: 'Гравитационная аномалия на границе горизонта событий. Сверхредкая темная материя и кристаллизованный астрит. Обитель Омега-Оверлорда.',
  },
};
